### ISSUE TITLE
Its not good its relly bad can it not be like pocketmine app

### ISSUE THREAD

**Issue by NetherOwner** [EnderManiacsKingdom/NetherManiacsKingdom-Android-Apk#1]

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
this is just the nethermaniacskingdom app, not the gladiatormine app

**Comment by NetherOwner** [comment]
Oh heahaya can you make the gladiatormine app

**Comment by matthew4444** [comment]
ill try,stay on though plz

**Comment by NetherOwner** [comment]
Kk

**Comment by NetherOwner** [comment]
And bro did you fix the issues with the startup

**Comment by matthew4444** [comment]
while u wiat, wanna play this game its an endless running game,i made it for my sister https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Frzs5hzzbe4zu3mz%2Fandroid-armv7-release.apk%3Fdl%3D1&sa=D&sntz=1&usg=AFQjCNGM5ky_jwpP_U-wXiBOGaM2h6tTVQ

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
thx

**Comment by NetherOwner** [comment]
And bro did you fix the issues with the startup

**Comment by matthew4444** [comment]
?

**Comment by matthew4444** [comment]
can u download this and give a link for the apk https://play.google.com/store/apps/details?id=net.pocketmine.server&hl=en ?

**Comment by NetherOwner** [comment]
Oh what you mean

**Comment by matthew4444** [comment]
download the app and backup the app via es file exploer and send the apk to mediafire and give the mediafire link here

**Comment by NetherOwner** [comment]
Oh

**Comment by matthew4444** [comment]
u doing it?

**Comment by matthew4444** [comment]
nvm i downloading apk

**Comment by NetherOwner** [comment]
K

**Comment by NetherOwner** [comment]
gladiatormine dosent work still

**Comment by matthew4444** [comment]
well what it say

**Comment by NetherOwner** [comment]
It dosent give a crashdump and then i saw the console and so it just say started server and closed server only that

**Comment by matthew4444** [comment]
it give u need installer msg?

**Comment by NetherOwner** [comment]
Nope

**Comment by matthew4444** [comment]
can u screenshot it
?

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
and upload screen shot here plz

**Comment by matthew4444** [comment]
hello?

**Comment by NetherOwner** [comment]
How

**Comment by NetherOwner** [comment]
![screenshot_2016-03-13-16-42-17](https://cloud.githubusercontent.com/assets/16944178/13729670/e068a4e8-e93a-11e5-981a-d7c41d78dce7.png)
![screenshot_2016-03-13-16-42-09](https://cloud.githubusercontent.com/assets/16944178/13729672/ea11fa94-e93a-11e5-807b-1f22884f36b1.png)

**Comment by matthew4444** [comment]
wow,extract this apk's contents and zip the folder's up and upload it here plz?

**Comment by NetherOwner** [comment]
What?

**Comment by matthew4444** [comment]
[net.zip](https://github.com/EnderManiacsKingdom/NetherManiacsKingdom-Android-Apk/files/171059/net.zip)

**Comment by matthew4444** [comment]
extract the apk contents to a folder and zip that folder up and upload it here plz

**Comment by matthew4444** [comment]
hello? ill brb 10-15 mins im taking a shower.plz stay on

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
thx

**Comment by NetherOwner** [comment]
[Uploading Download.zip…]()

**Comment by NetherOwner** [comment]
http://www.mediafire.com/?3vdg4i7a5558dnn Here is the pocketmine file

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
im coding the app thx

**Comment by NetherOwner** [comment]
Good and can you make this the background 
![maxresdefault](https://cloud.githubusercontent.com/assets/16944178/13729883/ca450d6e-e93f-11e5-9dde-1fc4e3eaaa23.jpg)

**Comment by matthew4444** [comment]
ill try

**Comment by NetherOwner** [comment]
Kk do you have a icon for gladiatormine if you have use that

**Comment by matthew4444** [comment]
![logo](https://cloud.githubusercontent.com/assets/6751780/13729898/21a311a2-e916-11e5-9091-31a1be80342a.png)

**Comment by NetherOwner** [comment]
But can you remove the planet and place something like gladiators

**Comment by matthew4444** [comment]
can u make the iicon,ur good at that plz,im editing the app still?

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
did u make the icon yet?

**Comment by NetherOwner** [comment]
Here is it do you like it 
![picsart_03-13-05 28 27](https://cloud.githubusercontent.com/assets/16944178/13729941/22a59b12-e941-11e5-801e-48b322fa29c2.jpg)

**Comment by NetherOwner** [comment]
Is it good

**Comment by matthew4444** [comment]
yas

**Comment by NetherOwner** [comment]
K use it

**Comment by matthew4444** [comment]
i will thx u very much

**Comment by NetherOwner** [comment]
I have a idea can we put it on the website gladiatormine.net

**Comment by NetherOwner** [comment]
Np

**Comment by matthew4444** [comment]
kk ask hitmanna so the person can put it on the fourms

**Comment by NetherOwner** [comment]
K

**Comment by NetherOwner** [comment]
How do i ask him like tell

**Comment by NetherOwner** [comment]
With email or what

**Comment by matthew4444** [comment]
YA

**Comment by matthew4444** [comment]
ON FOURMS

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
thx

**Comment by NetherOwner** [comment]
For what

**Comment by matthew4444** [comment]
the lgog

**Comment by matthew4444** [comment]
logo

**Comment by NetherOwner** [comment]
Oh np

**Comment by matthew4444** [comment]
can u find the pocketmien logo in the zip file u sent me , bc its hard to do on a micropc,and replace it with gladiatormine plz

**Comment by matthew4444** [comment]
hint the imgs are in the "/res" folder

**Comment by matthew4444** [comment]
how u make custom labels also in github?

**Comment by NetherOwner** [comment]
Kk

**Comment by NetherOwner** [comment]
All pictures of pocketmine is in drawable

**Comment by NetherOwner** [comment]
Folders

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
u on?

**Comment by NetherOwner** [comment]
Yes

**Comment by matthew4444** [comment]
kk did u do it?

**Comment by NetherOwner** [comment]
Do what

**Comment by matthew4444** [comment]
can u find the pocketmien logo in the zip file u sent me , bc its hard to do on a micropc,and replace it with gladiatormine plz

**Comment by NetherOwner** [comment]
Go all down and so you can see icon and hint all in drawable folders

**Comment by matthew4444** [comment]
?

**Comment by NetherOwner** [comment]
Omg can you see all drawable folders yes or no

**Comment by matthew4444** [comment]
did u finish the logo in the folders,and upload the zip and give me the link yet?

**Comment by NetherOwner** [comment]
Omg bro can you not just copy the logo i send you and replace it with the old logo

**Comment by matthew4444** [comment]
kk here (https://cloud.githubusercontent.com/assets/16944178/13729941/22a59b12-e941-11e5-801e-48b322fa29c2.jpg ?

**Comment by NetherOwner** [comment]
Ohh what

**Comment by NetherOwner** [comment]
Yes thata the logo so?

**Comment by matthew4444** [comment]
did u copy ur logo of gladiatormine and make it the app icon as i was asking for for so long?

**Comment by NetherOwner** [comment]
But did you not edit ohhhh omg

**Comment by matthew4444** [comment]
i didnt finish

**Comment by NetherOwner** [comment]
Can you not edit the app and so i gonna give you stuff and things plss

**Comment by matthew4444** [comment]
ok im still waiting

**Comment by NetherOwner** [comment]
For what

**Comment by matthew4444** [comment]
THE APP U FIXED THE LOGO'S WITH WTF MAN R U DRUNK WHAT DO U THINK

**Comment by NetherOwner** [comment]
Kk i gonna do it sorry i maked you mad

**Comment by matthew4444** [comment]
im srry for blwoing up

**Comment by NetherOwner** [comment]
Bro im done i replaced all the pocketmine logo with the gladiatormine logo 
[GladiatorMine.zip](https://github.com/EnderManiacsKingdom/NetherManiacsKingdom-Android-Apk/files/171119/GladiatorMine.zip)

**Comment by matthew4444** [comment]
thx

**Comment by NetherOwner** [comment]
Np

**Comment by matthew4444** [comment]
let me add the txt to say gladiatormine instead of pocketmine

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
u can look at my old site if you want in the meantime while i code it https://azaz09909.wapka.mobi

**Comment by NetherOwner** [comment]
And what about this background maybe you can make it to cartoon insted 
![gladiator-movie-wallpapers-3](https://cloud.githubusercontent.com/assets/16944178/13730208/244817d0-e949-11e5-8b40-18bd979ae5dc.jpeg)

**Comment by matthew4444** [comment]
i can try give me a min

**Comment by NetherOwner** [comment]
K

**Comment by NetherOwner** [comment]
Soo you done yet

**Comment by matthew4444** [comment]
when u hit info in gladiatormine app i will give apk as soon as i finish the the oether code ull see the background

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
u on?

**Comment by NetherOwner** [comment]
Yes

**Comment by NetherOwner** [comment]
![Uploading IMG_20160313_37766.jpg…]()

**Comment by matthew4444** [comment]
this will be what the about page in pocketmine app would look like (like it?) http://gladiatormine.net/gladiatormine-app-beta/assets/about.html

**Comment by NetherOwner** [comment]
Can you make the red and green to black and white

**Comment by matthew4444** [comment]
if i do it makes the text unreadable

**Comment by NetherOwner** [comment]
Oh but what about black and so red

**Comment by matthew4444** [comment]
?

**Comment by NetherOwner** [comment]
I have a idea give me  the text you typed

**Comment by NetherOwner** [comment]
.

**Comment by matthew4444** [comment]
https://n1plcpnl0070.prod.ams1.secureserver.net:2083/cpsess5117587470/frontend/gl_paper_lantern/filemanager/editit.html?file=about.html&fileop=&dir=%2Fhome%2Fdavidbrockway%2Fpublic_html%2Fgladiatormine.net%2Fgladiatormine-app-beta%2Fassets&dirop=&charset=&file_charset=_DETECT_&baseurl=&basedir= if it asks for pass tell me

**Comment by NetherOwner** [comment]
![picsart_03-13-07 06 19](https://cloud.githubusercontent.com/assets/16944178/13730407/ca0eaabc-e94e-11e5-9f53-4d3907cd5c74.jpg)

**Comment by matthew4444** [comment]
thhats  better

**Comment by NetherOwner** [comment]
Its ask for pass and username

**Comment by matthew4444** [comment]
user:davidbrockway and email netherkingdom2@gmail.com for pass

**Comment by matthew4444** [comment]
user:davidbrockway and email netherkingdom2@gmail.com for pass

**Comment by matthew4444** [comment]
hello?

**Comment by matthew4444** [comment]
anyone on?

**Comment by NetherOwner** [comment]
Here is this good 
![picsart_03-13-07 17 22](https://cloud.githubusercontent.com/assets/16944178/13730465/541afdfe-e950-11e5-9a36-edd5fea9a5ab.jpg)

**Comment by NetherOwner** [comment]
Hi

**Comment by matthew4444** [comment]
the html code plz

**Comment by matthew4444** [comment]
the html code for https://cloud.githubusercontent.com/assets/16944178/13730465/541afdfe-e950-11e5-9a36-edd5fea9a5ab.jpg

**Comment by matthew4444** [comment]
hello?

**Comment by NetherOwner** [comment]
K wait

**Comment by matthew4444** [comment]
kk

**Comment by NetherOwner** [comment]
It dosent have a html i dont know what the html is

**Comment by matthew4444** [comment]
u just edited the photo to add text didnt u?

**Comment by NetherOwner** [comment]
..

**Comment by NetherOwner** [comment]
Yes i did

**Comment by matthew4444** [comment]
did u add the text to the photo via photoshop?

**Comment by matthew4444** [comment]
ok

**Comment by NetherOwner** [comment]
No just with a app named picsart

**Comment by matthew4444** [comment]
i cant see  the text to the left of the image next to the person's right eye https://cloud.githubusercontent.com/assets/16944178/13730465/541afdfe-e950-11e5-9a36-edd5fea9a5ab.jpg

**Comment by NetherOwner** [comment]
Oh

**Comment by matthew4444** [comment]
can u fix it

**Comment by NetherOwner** [comment]
Yes wait

**Comment by NetherOwner** [comment]
Can you give me text

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
About GladiatorMine-MP for Android

GladiatorMine-MP is an open-source server software for Minecraft: Pocket Edition.

Create a server directly on your Android device, extend its features and manage it easily using plugins. Open it to the internet and play with your friends!

This application includes PHP, BusyBox (only killall patches) and GladiatorMine-MP.

This application itself is made by Matthew James Pitsicalis and GladiatorMine-MP (the server is made by the GladiatorMine team).

This application is based on DroidPHP, created by Shushant Kumar and licensed under Apache License v2.0! Thank you!

**Comment by matthew4444** [comment]
DO U KNOW PH,BC WE NEED PLUGIN THAT ABOSLEY HAVENT BEEN WORKED ON SINCE WE WERE AT HTTP://GITHUB.COM/NETHERMANIACSKINGDOM WE NEED TO WORK ON THEM NOW IM GETTING PISSED OFF BIG TIME. NOW STOP PHOTOSHOPPING AND CODE PHP PLZ WITH THE TEA,M PLZZZZZZ

**Comment by matthew4444** [comment]
TO DOLIST: 1. GLADIATORMINE APIS 2.THE REPOS IN THE ENDERMANIACSKINGDOM TEAM 3. AFTER THAT MAKING A BUISNNES WERE WE CAN SELL GLADIATORMINE AND PUT UPDATES TO IT, AND MAKE A BUISSNES OUT OF PLUGIN SELLIIMNG ALSO 4. MAKE A LARGER BUISSNESS AFTER A WHILE IF POSABLE ,AND ETC

**Comment by matthew4444** [comment]
U ON?

**Comment by NetherOwner** [comment]
Yes

**Comment by matthew4444** [comment]
OK READ WHAT I TYPED ABOVE

**Comment by NetherOwner** [comment]
Bro i dont know how to code only plugin.yml

**Comment by matthew4444** [comment]
OK THEN ILL START AND ULL GET IN AFTER A WHILE AFTER I START AAND ILL TELL U WHAT U NEED TO DO WHEN I SAY PLZ

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
K

**Comment by NetherOwner** [comment]
So what do i do

**Comment by matthew4444** [comment]
im adding shopcart to the api give me a sec

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
here how it goes

**Comment by matthew4444** [comment]
study this file from line's 1-60 https://github.com/EnderManiacsKingdom/GladiatorMine/blob/php7-0.14/src/pocketmine/plugin/Plugin.php first tell me when ur done

**Comment by NetherOwner** [comment]
K

**Comment by NetherOwner** [comment]
Yes

**Comment by NetherOwner** [comment]
Uh bro i saw 1 to 60 and nothing

**Comment by matthew4444** [comment]
hello

**Comment by NetherOwner** [comment]
Hi

**Comment by matthew4444** [comment]
hello

**Comment by matthew4444** [comment]
hello?

**Comment by NetherOwner** [comment]
So i maked plugin yml is that good

**Comment by matthew4444** [comment]
ur on

**Comment by NetherOwner** [comment]
Yes

**Comment by matthew4444** [comment]
ya its good did u code it ur self?

**Comment by NetherOwner** [comment]
Hey bro what do i do if my pocketmine mp phar say you must install 7.0 what do i do so

**Comment by NetherOwner** [comment]
Yeah i hope its rigth is it rigth

**Comment by NetherOwner** [comment]
I mean no i did not make it self

**Comment by matthew4444** [comment]
u need php7 but its not avaiable for android,our plugin dev team can make a php5 version,i would right now if i knew php though

**Comment by matthew4444** [comment]
brb 5-10 mins dinner

**Comment by NetherOwner** [comment]
Oh

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
i finsihed dinner lol

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
wht up

**Comment by NetherOwner** [comment]
I gonna try out gladiatormine now because i added plugin.yml

**Comment by matthew4444** [comment]
kk tell me if it works

**Comment by NetherOwner** [comment]
K

**Comment by NetherOwner** [comment]
Nope still not

**Comment by matthew4444** [comment]
kk we need to ask the team to make a php5 version of gladiatormine

**Comment by NetherOwner** [comment]
Why php5

**Comment by matthew4444** [comment]
bc pocketmine android uses php5 lol

**Comment by NetherOwner** [comment]
? What you mean

**Comment by matthew4444** [comment]
android pocketmine is old and uses php5 and php7 is gladiatormine

**Comment by NetherOwner** [comment]
Ohh

**Comment by NetherOwner** [comment]
Okay thats why it dont work on startup rigth?

**Comment by matthew4444** [comment]
ya and look what i found http://pmt.mcpe.me/pg and http://pmt.mcpe.me/pg/events.php

**Comment by NetherOwner** [comment]
Whats that?

**Comment by NetherOwner** [comment]
I mean what can it do

**Comment by matthew4444** [comment]
it can make plugins

**Comment by NetherOwner** [comment]
Cool

**Comment by matthew4444** [comment]
kk

**Comment by NetherOwner** [comment]
Can you make enderauth plss

**Comment by matthew4444** [comment]
how

**Comment by NetherOwner** [comment]
Nvm

**Comment by matthew4444** [comment]
guess wht

**Comment by NetherOwner** [comment]
What

**Comment by matthew4444** [comment]
im working on gladiatormine site

**Comment by NetherOwner** [comment]
So?

**Comment by matthew4444** [comment]
ill tell u when i finish

**Comment by NetherOwner** [comment]
Matthew i tryed enderauth and so its normal but it just after it just stop disable all plugins and stop server no crash dump what do i do

**Comment by matthew4444** [comment]
send cracshdump txt here

**Comment by matthew4444** [comment]
copy and paste the crashdump text here plz

**Comment by NetherOwner** [comment]
There is no crash dump

**Comment by NetherOwner** [comment]
Onky this

**Comment by NetherOwner** [comment]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [21:17:37] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [21:17:38] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [21:17:38] [Server thread/INFO]: Loading server properties...
[Server] [21:17:38] [Server thread/INFO]: Enable MainLogger to file
[Server] [21:17:38] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [21:17:38] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.x beta/alpha
[Server] [21:17:38] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [21:17:38] [Server thread/INFO]: This server is running ClearSky-Sunrise version 1.1 (API 1.13.1) Build 153
[Server] [21:17:38] [Server thread/INFO]: ClearSky is distributed under the LGPL License
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyAPI v2.0.9
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyAuction v2.0.2
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyCasino v2.0.2
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyJob v2.0.4
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyLand v2.0.9
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyProperty v2.0.6
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyPShop v2.0.2
[Server] [21:17:40] [Server thread/INFO]: Loading EconomySell v2.0.7
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyShop v2.0.7
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyTax v2.0.3
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyUsury v1.0.1
[Server] [21:17:40] [Server thread/INFO]: Loading Slapper v1.2.9.3
[Server] [21:17:40] [Server thread/INFO]: Loading iProtector v3.1b
[Server] [21:17:40] [Server thread/INFO]: Loading VoteReward v3.0.2
[Server] [21:17:40] [Server thread/INFO]: Loading ManyWorlds v2.0.3
[Server] [21:17:40] [Server thread/INFO]: Loading PeacefulSpawn v2.4
[Server] [21:17:40] [Server thread/INFO]: Loading Sheep v4.0.3
[Server] [21:17:40] [Server thread/INFO]: Loading WorldEditArt v1.0.0_beta_dev_#048
[Server] [21:17:40] [Server thread/INFO]: Loading TapToDo v2.2.1
[Server] [21:17:40] [Server thread/INFO]: Loading MassiveEconomy v1.0 R3
[Server] [21:17:40] [Server thread/INFO]: Loading CrateKeys v1.0.5
[Server] [21:17:40] [Server thread/INFO]: Loading FactionsPro v1.3.2
[Server] [21:17:40] [Server thread/INFO]: Loading Lightning_Strike v2
[Server] [21:17:40] [Server thread/INFO]: [Lightning_Strike] Preparing For StartUp... STAND BY
[Server] [21:17:40] [Server thread/INFO]: Loading ZipPluginLoader v1.1.3
[Server] [21:17:40] [Server thread/INFO]: Loading EconomyAirport v2.0.4
[Server] [21:17:40] [Server thread/INFO]: Loading MassiveEconomyExample v1
[Server] [21:17:40] [Server thread/INFO]: Enabling MassiveEconomy v1.0 R3
[Server] [21:17:40] [Server thread/INFO]: Enabling ZipPluginLoader v1.1.3
[Server] [21:17:40] [Server thread/INFO]: [ZipPluginLoader] Loading zip plugin EnderAuth v1.0.0
[Server] [21:17:40] [Server thread/INFO]: Enabling MassiveEconomyExample v1
[Server] [21:17:40] [Server thread/INFO]: [MassiveEconomyExample] Example Plugin using MassiveEconomy (API v0.90)
[Server] [21:17:40] [Server thread/INFO]: Preparing level "world"
[Server] [21:17:40] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
[Server] [21:17:41] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] [21:17:41] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
[Server] [21:17:46] [Server thread/NOTICE]: [EconomyAPI] 
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyAuction v2.0.2
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyCasino v2.0.2
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyJob v2.0.4
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyLand v2.0.9
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyProperty v2.0.6
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyPShop v2.0.2
[Server] [21:17:46] [Server thread/CRITICAL]: [EconomyPShop] [DEPENDENCY] Please install ItemCloud plugin to use PShop plugin.
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomySell v2.0.7
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyShop v2.0.7
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyTax v2.0.3
[Server] [21:17:46] [Server thread/INFO]: Enabling EconomyUsury v1.0.1
[Server] [21:17:46] [Server thread/INFO]: Enabling Slapper v1.2.9.3
[Server] [21:17:46] [Server thread/INFO]: Enabling iProtector v3.1b
[Server] [21:17:46] [Server thread/INFO]: Enabling VoteReward v3.0.2
[Server] [21:17:46] [Server thread/INFO]: Enabling ManyWorlds v2.0.3
[Server] [21:17:47] [Server thread/INFO]: Enabling PeacefulSpawn v2.4
[Server] [21:17:47] [Server thread/INFO]: Enabling Sheep v4.0.3
[Server] [21:17:47] [Server thread/INFO]: [Sheep] Loading configuration.
[Server] [21:17:47] [Server thread/INFO]: [Sheep] Setting up commands.
[Server] [21:17:47] [Server thread/INFO]: [Sheep] Done!
[Server] [21:17:47] [Server thread/INFO]: Enabling WorldEditArt v1.0.0_beta_dev_#048
[Server] [21:17:47] [Server thread/INFO]: Enabling TapToDo v2.2.1
[Server] [21:17:47] [Server thread/INFO]: Enabling CrateKeys v1.0.5
[Server] [21:17:47] [Server thread/INFO]: Enabling FactionsPro v1.3.2
[Server] [21:17:47] [Server thread/INFO]: Enabling Lightning_Strike v2
[Server] [21:17:47] [Server thread/INFO]: [Lightning_Strike] Lightning Strike RUNNING Made By MichaelM04
[Server] [21:17:47] [Server thread/INFO]: Enabling EconomyAirport v2.0.4
[Server] [21:17:47] [Server thread/INFO]: [ZipPluginLoader] Enabling EnderAuth v1.0.0
[Server] [21:17:47] [Server thread/INFO]: EnderAuth by NetherKingdom is starting up...
[Server] [21:17:47] [Server thread/INFO]: [EnderAuth] Upgrading config...
[Server] [21:17:47] [Server thread/INFO]: [EnderAuth] Config updated.
[Server] [21:17:50] [Server thread/INFO]: [EnderAuth] Creating players folder for provider...
[Server] [21:17:54] [Server thread/INFO]: Starting GS4 status listener
[Server] [21:17:54] [Server thread/INFO]: Setting query port to 19132
[Server] [21:17:54] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [21:17:54] [Server thread/INFO]: Default game type: Survival Mode
[Server] [21:17:54] [Server thread/INFO]: Done (22.195s)! For help, type "help" or "?"
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyAPI v2.0.9
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyAuction v2.0.2
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyCasino v2.0.2
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyJob v2.0.4
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyLand v2.0.9
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyProperty v2.0.6
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyPShop v2.0.2
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomySell v2.0.7
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyShop v2.0.7
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyTax v2.0.3
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyUsury v1.0.1
[Server] [21:17:54] [Server thread/INFO]: Disabling Slapper v1.2.9.3
[Server] [21:17:54] [Server thread/INFO]: Disabling iProtector v3.1b
[Server] [21:17:54] [Server thread/INFO]: Disabling VoteReward v3.0.2
[Server] [21:17:54] [Server thread/INFO]: Disabling ManyWorlds v2.0.3
[Server] [21:17:54] [Server thread/INFO]: Disabling PeacefulSpawn v2.4
[Server] [21:17:54] [Server thread/INFO]: Disabling Sheep v4.0.3
[Server] [21:17:54] [Server thread/INFO]: Disabling WorldEditArt v1.0.0_beta_dev_#048
[Server] [21:17:54] [Server thread/INFO]: Disabling TapToDo v2.2.1
[Server] [21:17:54] [Server thread/INFO]: [TapToDo] Saving blocks...
[Server] [21:17:54] [Server thread/INFO]: Disabling MassiveEconomy v1.0 R3
[Server] [21:17:54] [Server thread/INFO]: Disabling CrateKeys v1.0.5
[Server] [21:17:54] [Server thread/INFO]: Disabling FactionsPro v1.3.2
[Server] [21:17:54] [Server thread/INFO]: Disabling Lightning_Strike v2
[Server] [21:17:54] [Server thread/INFO]: Disabling ZipPluginLoader v1.1.3
[Server] [21:17:54] [Server thread/INFO]: [ZipPluginLoader] Disabling EnderAuth v1.0.0
[Server] [21:17:54] [Server thread/INFO]: Disabling EconomyAirport v2.0.4
[Server] [21:17:54] [Server thread/INFO]: Disabling MassiveEconomyExample v1
[Server] [21:17:54] [Server thread/INFO]: Unloading level "world"
[Server] [21:18:00] [Server thread/INFO]: Stopping other threads
[PocketMine] Server was stopped.

**Comment by matthew4444** [comment]
umm try

**Comment by NetherOwner** [comment]
Try what

**Comment by matthew4444** [comment]
umm try creating an enderauth folder in ur plugins folder and name it "EnderAuth"

**Comment by NetherOwner** [comment]
And so what

**Comment by NetherOwner** [comment]
Hurry i gonna sleep

**Comment by matthew4444** [comment]
try turning on ur server if u made taht folder and tell me what happens

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
kk

**Comment by NetherOwner** [comment]
The same

**Comment by NetherOwner** [comment]
It does the same thing

**Comment by matthew4444** [comment]
then create a "players" folder in the enderauth folder then tell me what happens

**Comment by NetherOwner** [comment]
But there is allredy a player folder in it

**Comment by NetherOwner** [comment]
And registered.txt but not a config

**Comment by matthew4444** [comment]
screenshot it and sen it

**Comment by matthew4444** [comment]
send

**Comment by NetherOwner** [comment]
Tjere is only player folder and registered.txt

**Comment by matthew4444** [comment]
kk

**Comment by NetherOwner** [comment]
What do i do

**Comment by NetherOwner** [comment]
Soo

**Comment by matthew4444** [comment]
im looking at config of enderauth and comparing it to what u have and ill tell u from there

**Comment by NetherOwner** [comment]
K but hurry i gonna sleep and i got only 5%

**Comment by NetherOwner** [comment]
And we are still not done with email.php so i delete it

**Comment by matthew4444** [comment]
u have charger

**Comment by NetherOwner** [comment]
Yes

**Comment by NetherOwner** [comment]
So are you done

**Comment by matthew4444** [comment]
im putting alundry away serrry

**Comment by NetherOwner** [comment]
Wow juwt plss hurrry!

**Comment by NetherOwner** [comment]
Its 22:42 and i gonna go to school tomorrow

**Comment by matthew4444** [comment]
i am,and get a chatrger

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
make a folder called "Resources" in enderauth folder and make a file called "config.yml" in resources and copythe text from here and paste it in config.yml https://github.com/NetherManiacsKingdom/WorkingInProgress-Plugins-Sourcecode-For-Dev/raw/master/EnderAuth/EnderAuth-Flaxues/resources/config.yml

**Comment by NetherOwner** [comment]
K

**Comment by matthew4444** [comment]
tell me what happens after that

**Comment by NetherOwner** [comment]
So what first do i gonna do make EnderAuth folder and so make resources folder or whar

**Comment by NetherOwner** [comment]
More details pls

**Comment by NetherOwner** [comment]
Hurry pls

**Comment by matthew4444** [comment]
make resources folder in enderauth then put config.yml in resourcesfrom here https://github.com/NetherManiacsKingdom/WorkingInProgress-Plugins-Sourcecode-For-Dev/raw/master/EnderAuth/EnderAuth-Flaxues/resources/config.yml

**Comment by NetherOwner** [comment]
K but what about the players folder and registered.txt do i delete them or what

**Comment by matthew4444** [comment]
kepep them,and now reload server and tell me what happens

**Comment by NetherOwner** [comment]
Kk

**Comment by matthew4444** [comment]
AND GET A CHARGER WHT PRECENT NOW

**Comment by NetherOwner** [comment]
Bro it just do the same issue

**Comment by matthew4444** [comment]
WTF IDK THEN,HOW MUCH PRECENT?

**Comment by NetherOwner** [comment]
Bye i gonna sleep

**Comment by matthew4444** [comment]
K

**Comment by NetherOwner** [comment]
Hi

**Comment by NetherOwner** [comment]
Did you find a way to fix enderauth

**Comment by matthew4444** [comment]
not yet
